# API configuration settings
server:
  host: "localhost"
  port: 8000

mimetypes:
  error: ["application/json"]
  json: ["application/json"]
  pdf: ["application/pdf"]
  docx: ["application/vnd.openxmlformats-officedocument.wordprocessingml.document"]

cors:
  enabled: true
  supports_credentials: false
  # origins: "*"
  origins:
    - "http://dev-app-alb-1479481766.us-east-2.elb.amazonaws.com"
    # - "http://localhost:8000"
    # - "http://127.0.0.1:8000"
    # - "http://0.0.0.0:8000"
  expose_headers:
    - "Content-Disposition"
    - "Content-Type"
    - "Content-Length"

input:
  prefer_file: true

output:
  use_temp_directory: true

logging:
  level: "INFO"
